services:
  authuser-server:
    build: ./authuser
    container_name: authuser-server
    ports:
      - "8087:8087"
    depends_on:
      authuser-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authuser-db:5432/authuserdb
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - backend

  authuser-db:
    image: postgres:16
    container_name: authuser-db
    restart: always
    volumes:
      - authuser-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: authuserdb
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userdb -d authuserdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  course-server:
    build: ./course
    container_name: course-server
    ports:
      - "8082:8082"
    depends_on:
      course-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-db:5432/coursedb
      SPRING_DATASOURCE_USERNAME: coursedb
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - backend
  course-db:
    image: postgres:16
    restart: always
    container_name: course-db
    volumes:
      - course-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: coursedb
      POSTGRES_USER: coursedb
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coursedb -d coursedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  authuser-db-data:
  course-db-data:
